Corrección de problema con transacciones en espera: ``` MWHWithholding.saveError: Error - ERROR: savepoint "jdbc_savepoint_2917" does not exist [77] ===========> Query.firstOnly: SELECT IsActive,Created,Updated,Value,EntityType,AD_Reference_ID,Description,ValidFrom,Name,ValidTo,AD_Ref_List_ID,AD_Org_ID,AD_Client_ID,CreatedBy,UpdatedBy,UUID FROM AD_Ref_List WHERE (AD_Reference_ID=? AND Value=?) [77] org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block; State=25P02; ErrorCode=0 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497) 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233) 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310) 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446) 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370) 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149) 	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108) 	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76) 	at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100) 	at com.sun.proxy.$Proxy49.executeQuery(Unknown Source) 	at org.compiere.model.Query.createResultSet(Query.java:781) 	at org.compiere.model.Query.firstOnly(Query.java:350) 	at org.compiere.model.MRefList.get(MRefList.java:62) 	at org.compiere.model.PO.set_Value(PO.java:874) 	at org.compiere.model.PO.set_Value(PO.java:755) 	at org.spin.model.X_WH_Withholding.setDocStatus(X_WH_Withholding.java:367) 	at org.compiere.process.DocumentEngine.prepareIt(DocumentEngine.java:412) 	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:290) 	at org.compiere.process.DocumentEngine.processIt(DocumentEngine.java:258) caused by: org.postgresql.util.PSQLException: ERROR: savepoint "jdbc_savepoint_2917" does not exist; State=3B001; ErrorCode=0 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497) 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233) 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310) 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446) 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370) 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:311) 	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:297) 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:274) 	at org.postgresql.jdbc.PgConnection.execSQLUpdate(PgConnection.java:440) 	at org.postgresql.jdbc.PgConnection.releaseSavepoint(PgConnection.java:1670) 	at com.mchange.v2.c3p0.impl.NewProxyConnection.releaseSavepoint(NewProxyConnection.java:1167) 	at org.compiere.util.Trx.releaseSavepoint(Trx.java:449) 	at org.compiere.model.PO.save(PO.java:2292) 	at org.compiere.model.PO.saveEx(PO.java:2310) 	at org.spin.util.AbstractWithholdingSetting.createWithholding(AbstractWithholdingSetting.java:431) 	at org.spin.util.AbstractWithholdingSetting.saveResult(AbstractWithholdingSetting.java:380) 	at org.erpya.lve.util.APInvoiceIVA.lambda$run$85(APInvoiceIVA.java:204) 	at java.util.ArrayList.forEach(ArrayList.java:1257) 	at org.erpya.lve.util.APInvoiceIVA.run(APInvoiceIVA.java:193) 	at org.spin.util.WithholdingEngine.processWithholding(WithholdingEngine.java:216) 	at org.spin.util.WithholdingEngine.processWithholding(WithholdingEngine.java:191)
===========> Query.first: SELECT
PriceLimit,PriceActual,QtyInvoiced,Created,Updated,C_ProjectPhase_ID,A_Asset_ID,IsActive,ReversalLine_ID,Description,FM_Amortization_ID,Processed,IsFixedAssetInvoice,C_ProjectTask_ID,GenerateTo,C_InvoiceLine_ID,User3_ID,User4_ID,IsPrinted,C_Project_ID,TaxAmt,LineTotalAmt,QtyEntered,User1_ID,C_Campaign_ID,C_Activity_ID,User2_ID,RRAmt,A_Processed,A_Asset_Group_ID,RRStartDate,IsDescription,A_CreateAsset,LineNetAmt,PriceEntered,A_CapvsExp,PriceList,AD_OrgTrx_ID,IsCollectiveAsset,Ref_InvoiceLine_ID,CreatedBy,C_Invoice_ID,AD_Client_ID,AD_Org_ID,Line,M_InOutLine_ID,C_Tax_ID,C_UOM_ID,C_Charge_ID,C_OrderLine_ID,M_Product_ID,S_ResourceAssignment_ID,M_RMALine_ID,M_AttributeSetInstance_ID,UpdatedBy,UUID,WM_InOutBoundLine_ID,InvoiceToAllocate_ID,DD_FreightLine_ID
FROM C_InvoiceLine WHERE (C_InvoiceLine_ID = ?) [1743]
org.postgresql.util.PSQLException: ERROR: current transaction is
aborted, commands ignored until end of transaction block; State=25P02;
ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy49.executeQuery(Unknown Source)
	at org.compiere.model.Query.createResultSet(Query.java:781)
	at org.compiere.model.Query.first(Query.java:315)
	at org.erpya.lve.model.LVE.modelChange(LVE.java:442)
	at org.compiere.model.ModelValidationEngine.lambda$null$15(ModelValidationEngine.java:376)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
caused by: org.postgresql.util.PSQLException: ERROR: savepoint
"jdbc_savepoint_2917" does not exist; State=3B001; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:311)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:297)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:274)
	at org.postgresql.jdbc.PgConnection.execSQLUpdate(PgConnection.java:440)
	at org.postgresql.jdbc.PgConnection.releaseSavepoint(PgConnection.java:1670)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.releaseSavepoint(NewProxyConnection.java:1167)
	at org.compiere.util.Trx.releaseSavepoint(Trx.java:449)
	at org.compiere.model.PO.save(PO.java:2292)
	at org.compiere.model.PO.saveEx(PO.java:2310)
	at org.spin.util.AbstractWithholdingSetting.createWithholding(AbstractWithholdingSetting.java:431)
	at org.spin.util.AbstractWithholdingSetting.saveResult(AbstractWithholdingSetting.java:380)
	at org.erpya.lve.util.APInvoiceIVA.lambda$run$85(APInvoiceIVA.java:204)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.erpya.lve.util.APInvoiceIVA.run(APInvoiceIVA.java:193)
	at org.spin.util.WithholdingEngine.processWithholding(WithholdingEngine.java:216)
	at org.spin.util.WithholdingEngine.processWithholding(WithholdingEngine.java:191)
```